# Generated by Django 2.2.4 on 2019-09-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_text', models.CharField(default='null', max_length=200)),
                ('pub_date', models.DateTimeField(default='null', verbose_name='date Published')),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='polls.Product'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
